default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary: &development_primary
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *development_primary
    migrations_paths: db/cache_migrate
  queue:
    <<: *development_primary
    migrations_paths: db/queue_migrate
  cable:
    <<: *development_primary
    migrations_paths: db/cable_migrate

test:
  primary: &test_primary
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *test_primary
    migrations_paths: db/cache_migrate
  queue:
    <<: *test_primary
    migrations_paths: db/queue_migrate
  cable:
    <<: *test_primary
    migrations_paths: db/cable_migrate

production:
  primary: &production_primary
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *production_primary
    migrations_paths: db/cache_migrate
  queue:
    <<: *production_primary
    migrations_paths: db/queue_migrate
  cable:
    <<: *production_primary
    migrations_paths: db/cable_migrate
